name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout misshod
        uses: actions/checkout@v4
        with:
          path: misshod
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.16.0
      - name: Build test
        run: zig build test
        working-directory: misshod
      - name: Build lib
        run: zig build
        working-directory: misshod

